In [14]:
import numpy as np

In [15]:
import cv2

In [3]:
img = cv2.imread('logo.jpg')

In [ ]:
cv2.waitKey(0)

In [ ]:
cv2.destroyAllWindows()

In [ ]:
cv2.imshow('image', img)

In [ ]:
end

In [ ]:
cv2.imshow('image', img)

In [1]:
import numpy as np

In [2]:
import cv2

In [3]:
img = cv2.imread('logo.jpg')

In [4]:
cv2.imshow('image',img)

In [5]:
cv2.waitKey(0)

99

In [6]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

NameError: name 'image' is not defined

In [ ]:
cv2.imshow('Gray Image', gray)

In [ ]:
cv2.destroyAllWindows()

In [ ]:
cv2.waitKey(0) & 0xFF

In [ ]:
cv2.destroyAllWindows & 0xFF

In [ ]:
0

In [1]:
import numpy as np

In [2]:
import cv2

In [3]:
img = cv2.imread('logo.jpg')

In [4]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

NameError: name 'image' is not defined

In [5]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [6]:
cv2.imshow('image',img)

In [7]:
cv2.imshow('Gray Image', gray)

In [8]:
cv2.waitKey(0)

99

In [7]:
cv2.destroyAllWindows()

In [10]:
print(img.shape)

(885, 1400, 3)


In [11]:
matrix2 = img[437:446, 695:704,:]

In [12]:
cv.imshow(matrix2)

NameError: name 'cv' is not defined

In [13]:
cv2.imshow(matrix2)

TypeError: imshow() missing required argument 'mat' (pos 2)

In [14]:
matrix = img[437:446, 695:704]

In [15]:
print(matrix)

[[[ 55  99 158]
  [ 43  97 152]
  [ 48 102 157]
  [ 45  99 154]
  [ 51 102 158]
  [ 51 102 158]
  [ 34  83 139]
  [ 38  87 143]
  [ 73 122 178]]

 [[ 60 105 166]
  [ 61 121 175]
  [ 63 120 175]
  [ 77 134 189]
  [ 82 138 193]
  [ 52 108 163]
  [ 28  82 137]
  [ 52 106 161]
  [ 95 149 204]]

 [[ 87 132 193]
  [ 65 127 181]
  [ 53 115 169]
  [ 78 138 192]
  [ 87 147 201]
  [ 59 116 171]
  [ 56 113 168]
  [ 79 136 191]
  [ 83 139 194]]

 [[ 72 130 189]
  [ 71 138 195]
  [ 91 155 213]
  [ 90 153 211]
  [ 69 129 188]
  [ 45 103 162]
  [ 65 119 179]
  [ 97 149 209]
  [ 81 133 193]]

 [[ 73 131 190]
  [ 89 153 211]
  [ 74 137 195]
  [ 66 126 185]
  [ 71 129 188]
  [ 57 113 172]
  [ 52 106 166]
  [ 78 130 190]
  [ 84 134 194]]

 [[ 92 150 209]
  [110 168 227]
  [ 62 120 179]
  [ 41  97 156]
  [ 68 122 182]
  [ 59 111 171]
  [ 28  78 138]
  [ 43  93 153]
  [ 69 116 177]]

 [[120 178 237]
  [118 174 233]
  [ 73 127 187]
  [ 48 102 162]
  [ 76 128 188]
  [ 69 119 179]
  [ 29  79 139]
  [ 41  88 1

In [16]:
cv2.imshow('normal image', img)

In [17]:
cv2.imshow('mod image', matrix)

In [18]:
cv2.waitKey(0)

99

In [19]:
cv2.destroyAllWindows()

In [8]:
print(img.shape)

(885, 1400, 3)


In [11]:
for i in range(0, 884, 20):
    for j in range(0, 1399, 10):
        img[i,j] = 0

In [12]:
cv2.imshow('changed', img)

In [13]:
cv2.waitKey(0)

99

In [14]:
cv2.destroyAllWindows()

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [18]:
flippedImg = cv2.flip(img, 1)

In [20]:
a = np.zeros(shape=(1670, 2800))

In [21]:
a[0:884, 0:1399] = img

ValueError: could not broadcast input array from shape (885,1400,3) into shape (884,1399)

In [7]:
A = {1, 2, 3, 
     4, 5, 6}

In [8]:
A

{1, 2, 3, 4, 5, 6}

In [9]:
A = [[1,2,3],[4,5,6]]

In [10]:
A

[[1, 2, 3], [4, 5, 6]]

In [11]:
A[0]

[1, 2, 3]

In [13]:
A[0][0]

1

In [16]:
B = [[7, 8, 9], [10, 11, 12]]

In [21]:
np.subtract(A,B)

array([[-6, -6, -6],
       [-6, -6, -6]])